jazzband/django-model-utils

.travis.yml, model_utils/managers.py, model_utils/models.py
=> Django 1.8+ compatibility

model_utils/fields.py
Hardcoding `no_excerpt_field=True` in deconstruct() method of SplitField class
=> Fix #169 issue

LICENSE.txt, docs/conf.py
=> Update copyright years to 2015

.gitignore, AUTHORS.rst, CHANGES.rst, CONTRIBUTING.rst, MANIFEST.in, model_utils/locale/de/LC_MESSAGES/django.po, setup.py
Includes changes in setup.py to enable automatic compilation and installation of django message catalogs.
=> German translations

CHANGES.rst, model_utils/managers.py
This PR adds compatibility with Django `1.10`.
Fixes #184
=> Support for Django 1.10

docs/utilities.rst
=> Docs update: has_changed supports a single field

AUTHORS.rst, CHANGES.rst, docs/managers.rst, docs/models.rst, model_utils/managers.py, model_utils/models.py, model_utils/tests/models.py, model_utils/tests/tests.py
SoftDeletableModel and friends - abstract model that instead of deleting entry marks it as deleted.
=> Add SoftDeletableModel

model_utils/fields.py, model_utils/tests/models.py, model_utils/tests/tests.py, tox.ini
This PR add tests to explain the issue #241.
=> Tests to demonstrate recursion error with double MonitorField and defer()/only() usage

CHANGES.rst, model_utils/managers.py, model_utils/tests/managers.py, model_utils/tests/models.py, model_utils/tests/test_managers/__init__.py, model_utils/tests/test_managers/test_softdelete_manager.py
Fixes issue described in #249. Add tests to cover the use case.
=> Fix issue when extend QuerySet and Manager - fixes #249

.travis.yml, tox.ini
This will help fix https://github.com/jazzband/roadies/issues/79.
=> Simplified tox setup with tox-travis.

docs/setup.rst
Docs inaccurately say django versions supported
Say Django 2.0 is supported
not needed
=> Update docs to support django 2.0

README.rst
Described in #340 
Change supported version number
=> Change supported version to 2.1 at README.rst (Fix #340)

.gitignore, Makefile, docs/fields.rst, docs/models.rst
`make init` will now create the VENV if needed.
=> Improve Makefile to handle VENV creation if needed.

.travis.yml, CHANGES.rst, docs/setup.rst, model_utils/choices.py, model_utils/fields.py, model_utils/managers.py, model_utils/tracker.py, setup.py, tests/models.py, tests/test_fields/test_field_tracker.py, tox.ini
Drop Python 2 support.
https://github.com/jazzband/django-model-utils/issues/393
=> Drop Python 2 support.

CHANGES.rst
i forgot to change changes file to explain the feature below, updating accordingly:
https://github.com/jazzband/django-model-utils/commit/3e32ae257b27cae9e91844e646ed099dca5c3869
=> added explanation for the new feature

CHANGES.rst, requirements-test.txt
=> Update test requirements.

README.rst
Added Python and Django supported versions to README.rst
=> Added Python and Django supported versions to README.rst

.travis.yml, README.rst, setup.py, tox.ini
=> Add Python39 support and drop Django2.1 support

.travis.yml, tests/test_models/test_status_model.py, tox.ini
=> Travisci flake8

CHANGES.rst
=> Release 4.1.0

CHANGES.rst, CONTRIBUTING.rst, Makefile, model_utils/__init__.py, model_utils/fields.py, model_utils/managers.py, model_utils/models.py, setup.cfg, setup.py, tests/managers.py, tests/models.py, tests/test_fields/test_field_tracker.py, tests/test_fields/test_monitor_field.py, tests/test_fields/test_status_field.py, tests/test_inheritance_iterable.py, tests/test_managers/test_inheritance_manager.py, tests/test_managers/test_join_manager.py, tests/test_managers/test_status_manager.py, tests/test_models/test_savesignalhandling_model.py, tests/test_models/test_status_model.py, tests/test_models/test_timeframed_model.py, tests/test_models/test_uuid_model.py, tox.ini
Added isort to this project refs #402  
- applied isort
- added to `tox` envs
- added to `travis.yml`
- added to `makefile`
- added note to contributing guide
- used black profile
- updated changelog
=> Used isort to sort imports

CHANGES.rst
This PR updates the `CHANGES.rst` file for a new release
=> Update CHANGES.rst for new release

model_utils/tracker.py
The `init_deferred_fields` method, added in https://github.com/jazzband/django-model-utils/commit/6ffae1ad8ffcfa6f9c3354e34f9ee5415e656f62, had its only usage removed in e6c7b567d1b03df8123eb6f8ae2706b37a602513.
Remove the `init_deferred_fields` method, along with the now-unused `DescriptorMixin`.
=> Remove dead `init_deferred_fields` method

CHANGES.rst, docs/managers.rst, model_utils/managers.py
This PR is a replacement for #613.
=> Deprecate `JoinManager` and `JoinManagerMixin`

CHANGES.rst
=> Release 5.0.0

.github/workflows/test.yml, CHANGES.rst, docker-compose.yml, requirements-mypy.txt, requirements-test.txt, setup.py, tests/test_fields/test_field_tracker.py, tox.ini
Update test matrix to include Django 5.2 and add classifier
=> Add formal support for Django 5.2
