- AUTHORS.rst
- model_utils/managers.py
- model_utils/tests/tests.py
Model example:
```python
class Place(models.Model):
objects = InheritanceManager()
name = models.CharField(max_length=64, null=True, blank=True)
```
`Place.objects.values('id').filter(name='Somewhere')`
```python
----> 1 Place.objects.values('id').filter(name='Somewhere')
/django/db/models/query.pyc in filter(self, *args, **kwargs)
677         set.
678         """
--> 679         return self._filter_or_exclude(False, *args, **kwargs)
680
681     def exclude(self, *args, **kwargs):
/django/db/models/query.pyc in _filter_or_exclude(self, negate, *args, **kwargs)
691                 "Cannot filter a query once a slice has been taken."
692
--> 693         clone = self._clone()
694         if negate:
695             clone.query.add_q(~Q(*args, **kwargs))
/django/db/models/query.pyc in …
```
> Backwards compatibility issue: fix _clone signature for Django<1.9

- tox.ini
A release that supports 1.9 would be nice.
> Start testing against Django 1.9 stable

- AUTHORS.rst
- CHANGES.rst
- model_utils/managers.py
- model_utils/tests/tests.py
After upgrading an application to Django 1.9 that uses django-model-utils for polymorphic models, I encountered a bug:
Whenever `values_list` was called on an InheritanceQuerySet, `AttributeError` would be raised complaining about either `tuple`(in case of `flat` parameter being false) or `integer`(or any other primitive variable type that's defined for the model and used in `values_list`) in case of `flat` being true, not having an attribute of `insert_child_model_name_here`.
This is a bugfix for that, which adds type checking to `_get_sub_obj_recurse` function.
I also added a new test case `test_dj19_values_list_on_select_subclasses`, that exercises this bug.
Fastest way to reproduce:
- Check out this branch
- Comment out my changes in managers.py L165:168
- Run test cases
> Fixed a bug with Django >= 1.9 and values_list being called on InheritanceQuerySet

- .travis.yml
- model_utils/tracker.py
Fixes #232 
So two things going on here.
First, as of Django 1.8, we should be using `get_deferred_fields` rather than manually probing for `isinstance(field_obj, DeferredAttribute)`.
Second, as of Django 1.10, it seems inherited models don't pull through the deferred fields in `__class__.__dict__`. Have to consult the base class to get them. I have a feeling this might be a regression and will probs raise a ticket with django to make sure, but this bandaid should work for the time being. There's a slight niggle in that dj110 now supports overriding fields from the base class. I _think_ I'm building the dict in the correct order so that stuff is overridden correctly, but there might need to be additional tests added to check for this (can open a new issue). Also, perhaps there's a way to …
> Django 1.10 support for FieldTracker

- AUTHORS.rst
- CHANGES.rst
- model_utils/tests/models.py
- model_utils/tests/tests.py
- model_utils/tracker.py
For deferred `FileField` Django 1.10 returns `FileDescriptor`, not a `DeferredAttribute`.
As a result, code
class MyModel(models.Model):
some_file = models.FileField(upload_to='test_location')
tracker = FieldTracker()
obj = MyModel.objects.defer('some_file')[0]
obj.tracker.changed()
raises exception like this:
Traceback (most recent call last):
File "/Users/stalk/develop/libs/django-model-utils/django-model-utils/model_utils/tests/tests.py", line 1808, in test_post_save_previous
deferred_instance = self.tracked_class.objects.defer('some_file')[0]
File "/Users/stalk/develop/libs/django-model-utils/django-model-utils/.tox/py27-django110/lib/python2.7/site-packages/django/db/models/query.py", line 295, in __getitem__
return list(qs)[0]
File …
> Support Django 1.10 deferred FileField with FieldTracker

- model_utils/models.py
- model_utils/tests/tests.py
When deleting a SoftDeletableModel instance, the `using` parameter should be passed down to the `save()` method.
https://docs.djangoproject.com/en/1.10/topics/db/multi-db/#selecting-a-database-for-save
> SoftDeletableModel: use correct DB connection

- model_utils/tests/tests.py
- tox.ini
Solution proposed to fix #206 
On a general way, we should use `freezegun` if we want to test anything related to values generated with `now()`.
> Update tests to use freezegun to avoid time resolution issues on Windows

- CHANGES.rst
2 pull requests - #239 and #240 - I've submitted recently aren't mentioned at the top of the changelog. Adding them [to minimise the effort](http://keepachangelog.com/) required when the next release will be done.
On a related note, what do you think of adding a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) with a checklist? One of the items could be to add an entry at the top of the changelog.
> Update changelog about 2 recent pull requests

- .travis.yml
- CHANGES.rst
- README.rst
- docs/managers.rst
- docs/setup.rst
- model_utils/fields.py
- model_utils/managers.py
- model_utils/tests/helpers.py
- model_utils/tests/models.py
- model_utils/tests/test_fields/__init__.py
- model_utils/tests/test_fields/test_field_tracker.py
- model_utils/tests/test_managers/__init__.py
- model_utils/tests/test_managers/test_inheritance_manager.py
- model_utils/tests/test_miscellaneous.py
- model_utils/tests/test_models/__init__.py
- model_utils/tests/tests.py
- setup.py
- tox.ini
- Drops support for anything below Django 1.8 (current LTS release)
- ~~Cleans up some pep8 E303 warnings. I can remove this commit - just went ahead because my editor lit up like a christmas tree.~~
- ~~Resolves 183~~.
- Supersedes / closes #162.
- Supersedes / closes #204.
> Drop unsupported Django versions

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Fixes #254
Adding Issue and Pull Request templates into `.github/` folder.
> Pull request and issue template fixes #254

- runtests.py
Some remaining compatibility code is remaining in `runtests.py` after #212 big cleaning.
Remove this compatibility code, as it is no more needed.
> Remove compatibility code in runtests.py file

- setup.py
Services such as https://pyup.io grab license info from package metadata to display alongside each requirement. django-model-utils isn't providing that license info in it's metadata.
Add a ``license`` argument to the ``setup()`` call in setup.py
> Add "license" arg to setup() call

- CHANGES.rst
- model_utils/managers.py
Django starting with 1.9 switched to using a class to provide an
iterator for the querymanager.  Between 1.9 and 1.10 changes slowly
stopped referencing that function and instead started calling
_iterator_class directly.
As the functionality model-utils is patching has moved, this patch moves
the iterator logic to a class to match the changes that have been made
in Django in version 1.9.
As Django 1.8 is a LTS release that is still supported, iterator()
is retained in the InheritanceQuerySetMixin and can be removed when
support for Django 1.8 is removed.  This goes for the try-except in the
import statements as well.
> Support django 1.11 iterator changes

- .travis.yml
- model_utils/managers.py
- tox.ini
See https://github.com/jazzband/django-model-utils/issues/297#issue-280210103
This covers a few areas
- Updating tox to test django 2.0
- Upgrading travis for django 2.0
- Use ``_chain`` in django 2.0 query chaining instead of ``_clone``
- Remove ``use_for_related_fields = True`` in favor of the new MRO for managers
Fixes #297
> Django 2.0 support

- AUTHORS.rst
The AUTHORS file does not display properly when parsed as ReStructuredText: https://github.com/jazzband/django-model-utils/blob/68bc61e82517cb01fa36c0d007091a8670425913/AUTHORS.rst
Add a pipe character at the beginning of each line so that all authors are not concatenated together when ReStructuredText is parsed.
> Fix AUTHORS.rst formatting.

- .travis.yml
- AUTHORS.rst
- CHANGES.rst
- model_utils/__init__.py
- model_utils/managers.py
- model_utils/tracker.py
- tests/models.py
- tests/test_fields/test_field_tracker.py
- tests/test_managers/test_inheritance_manager.py
- tests/test_models/test_deferred_fields.py
- tox.ini
Fixes #278. cc @utapyngo @djstein 
Prior to Django 1.10, deferred attributes were handled by constructing a new model class with custom descriptors for the deferred attributes. After 1.10, deferred fields are tracked by whether the attribute is present in the instance `__dict__`.
`FieldTracker` handled tracking on these fields by overwriting the descriptors on the model class. This means that in 1.10+, the instance model class _is_ the model, so `FieldTracker` can introduce changes to the base class whenever deferred fields are used that persist on other queries. #278 This is reproduced in a test case.
I updated the `finalize_class` method to _wrap_ field descriptors. This preserves the custom descriptor behavior, and means that deferring fields does not lead to permanent changes in base …
> Fix handling of deferred fields on django 1.10+

- AUTHORS.rst
- CHANGES.rst
- docs/utilities.rst
- model_utils/tracker.py
- tests/test_fields/test_field_tracker.py
Currently `has_changed()` and `previous()` do not return correct values when working with Django deferred fields.
* `previous()` always returns `None`, even if the deferred value in the database is not `None`.
* `has_changed()` always returns `True`, even if the field has not changed. It also has the side-effect of unnecessarily fetching deferred fields from the database.
* This means that calling `tracker.changed()` unnecessarily loads all deferred fields, which can have a meaningful performance impact.
Here is a simplified real-life example that shows why this would be useful to fix:
for instance in MyModel.objects.defer('giant_text_field'):
if instance.needs_update:
instance.giant_text_field = download_giant_text_file(instance)
if instance.tracker.changed():
instance.save()
The goal …
> Handle deferred fields in FieldTracker.has_changed() and previous()

- model_utils/__init__.py
- model_utils/choices.py
- model_utils/fields.py
- model_utils/managers.py
- model_utils/tracker.py
- tests/models.py
- tests/test_choices.py
- tests/test_fields/test_field_tracker.py
- tests/test_fields/test_status_field.py
- tests/test_managers/test_inheritance_manager.py
- tests/test_models/test_deferred_fields.py
- tests/test_models/test_status_model.py
- tox.ini
@tony @carljm 
One of the checkboxes in the PR checklist ("Write PEP8 compliant code.") wasn't covered in #317, since there were many pep8 violations already present in the repo. I said I would fix flake8 violations in another pull request.
I added a `flake8` tox environment which runs flake8 to enforce pep8-style code formatting. I've ignored the following errors:
Personally this one always struck me as sort of silly and pedantic. I don't think it improves code readability, and can sometimes detract from it. I can fix the violation of this rule if requested.
I think this actually leads to less readable code in many cases, since violating this allows showing the operator connecting the two lines at the beginning of the line (emphasized) rather than the end (deemphasized). As before, I can …
> Fix pep8 violations

- CHANGES.rst
- model_utils/tracker.py
- tests/settings.py
- tests/test_fields/test_field_tracker.py
see #330 for more details, shortly:
`AttributeError: Can't pickle local object 'FieldTracker.patch_save.<locals>.save'`
Original code stored patched `save` method in `instance.__dict__`, breaking django cache system. 
PR proposes to patch model class save instead at `FieldTracker.contribute_to_class`.
> fix #330 patch MyModel.save instead of MyModel().save

- .coveragerc
- .travis.yml
- AUTHORS.rst
- README.rst
- docs/managers.rst
- model_utils/managers.py
- requirements-test.txt
- tests/models.py
- tests/settings.py
- tests/test_managers/test_inheritance_manager.py
- tests/test_managers/test_join_manager.py
- tox.ini
Implementing the suggestion as described in #348. 
The PR does the following things
- Updates coveragerc to include all relevant files, not all files were included before. Hence codecoverage complaining
- Replace sqlite3 with postgres for better reliability (also you can't run several statements in a cursor in sqlite3 which is another reason for opting for postgres). 
- Implementing the suggestion in #348 
- Dropping django 1.8. The field `rel`, was not available and django 1.8 is way out of date anyway so it's better to drop it all together. 
Solution in this PR. Instead of using sqlite, it's also using postgres.
> Add a JoinManager that helps with performance

- CHANGES.rst
- model_utils/choices.py
- tests/test_choices.py
`reversed(choices)` doesn’t work in all cases #309 
Implemented `Choices.__reversed__`.
> Add support for reverse iteration of Choices

- CHANGES.rst
- model_utils/models.py
As per issue #255, there is currently no way to directly query for soft deleted objects
Added a default Manager as `all_objects` on the SoftDeletableModel
> Add default manager as all_objects for SoftDeletableModel

- CHANGES.rst
- model_utils/tracker.py
- tests/settings.py
- tests/test_fields/test_field_tracker.py
After #350 django model with tracker can't call save with args:
```
return super().save(force_insert, force_update, using, update_fields)
TypeError: save() takes 1 positional argument but 5 were given 
```
Add `*args` to patched_save.
> fix model.save patched in FieldTracker

- CHANGES.rst
- requirements-test.txt
- tox.ini
Solves #359: Travis build is failing
Changed tests requirements upgrading:
- pytest
- pytest-django
- pytest-cov
> Upgrades pytest, pytest-django and pytest-cov version to fix travis build

- CHANGES.rst
- model_utils/managers.py
- tests/models.py
- tests/test_managers/test_inheritance_manager.py
If a child model needs a `OneToOneField` with any of its parent class that use `InheritanceManager` along with the usual `parent_link` generated by Django, `model_utils` adds by mistake the reverse link of this relation to the usual list of possible subclasses. Depending of the length of the classes names, and the depth of the class tree, a bug may be triggered or not, resulting in a child object being cast to the wrong class (basically one with a longer name).
When building the list of possible subclasses, check that `parent_link` is `True` before adding the class to the list.
> managers: honor OneToOneField.parent_link=False

- AUTHORS.rst
- CHANGES.rst
- docs/models.rst
I incorporated what @kezabelle wrote in https://github.com/jazzband/django-model-utils/issues/118#issuecomment-38028971 into a pull request.
Wasn't sure if I had to modify `AUTHORS.rst` and `CHANGES.rst` but I figured I would take [`CONTRIBUTING.rst`](https://github.com/jazzband/django-model-utils/blob/1b9b5ac2c180ece8d418ddbf277e9d944979003a/CONTRIBUTING.rst) word for word to be safe.
> Explain usage of timeframed model manager in the documentation

- CHANGES.rst
- model_utils/tracker.py
- tests/models.py
- tests/test_fields/test_field_tracker.py
Fixes #331.
Catch the `AttributeError` and return the underlying field value.
> Catch deferred attribute exception

- model_utils/tracker.py
- tests/models.py
This fixes a regression added by #350. There is currently a non-deterministic failure to apply `FieldTracker.patch_save()` to models that have their own save method. For example:
```
class Tracked(models.Model):
tracker = FieldTracker()
def save(self, *args, **kwargs):
super(Tracked, self).save(*args, **kwargs)
print(Tracked.save)
```
If `patch_save` fails, then the field tracker doesn't properly reset after calling save.
The reason for this nondeterminism is that Django's ModelBase metaclass (prior to 2.2) copies attributes to the model in dictionary order, so the `patch_save()` call in `FieldTracker. contribute_to_class` only lasts if `'save'` happens to come before `'tracker'` in the attr dictionary's keys.
(Here's the [Django code prior to …
> Move patch_save to finalize_class so it works on models with save() methods

- AUTHORS.rst
- CHANGES.rst
- docs/fields.rst
- docs/models.rst
- model_utils/exceptions.py
- model_utils/fields.py
- model_utils/models.py
- tests/models.py
- tests/test_fields/test_uuid_field.py
- tests/test_models/test_uuid_model.py
This fix #332 and the interest to have a UUIDModel that override pk primary key with an uuid field.
This abstract base class UUIDModel provides id field on any model that inherits from it which will be the primary key.
Also implements an UUIDField so If you dont want to set id as primary key or change the field name, you can do it overriding it with the custom field.
You can set the uuid version. Versions 1,3,4 and 5 are supported, default is 4.
> Add UUIDModel and UUIDField

- CHANGES.rst
Planning on tagging this change with the `3.2.0` to kickoff the release process once it's merged.
Looks like version number was already bumped in https://github.com/jazzband/django-model-utils/commit/05671695bb347fea57fcf33c2f0897d918184819 but never release, not sure why.
Fixes #366
> Release 3.2.0.

- model_utils/fields.py
- model_utils/models.py
- tests/models.py
- tests/signals.py
- tests/test_models/test_savesignalhandling_model.py
```
model_utils/fields.py:287:1: W293 blank line contains whitespace
model_utils/fields.py:291:1: W293 blank line contains whitespace
model_utils/fields.py:295:1: W293 blank line contains whitespace
model_utils/fields.py:303:33: W291 trailing whitespace
model_utils/fields.py:304:1: W293 blank line contains whitespace
model_utils/models.py:110:67: W504 line break after binary operator
model_utils/models.py:199:38: E713 test for membership should be 'not in'
model_utils/models.py:212:38: E713 test for membership should be 'not in'
tests/signals.py:4:1: E302 expected 2 blank lines, found 1
tests/models.py:7:1: F401 'django.dispatch.receiver' imported but unused
tests/models.py:84:1: E302 expected 2 blank lines, found 1
tests/test_models/test_savesignalhandling_model.py:30:5: E303 too many …
```
> Fixed flake8 issues.

- AUTHORS.rst
- CHANGES.rst
- docs/utilities.rst
- model_utils/__init__.py
- model_utils/choices.py
- tests/test_choices.py
Throughout a project I'm working on, there are lines such as this:
```python3
failure_reason = forms.ChoiceField(
...,
choices=tuple(Model.CHOICES)[1:3],
)
```
Which are unreadable and fragile.
With this PR, they can be changed to:
```python3
failure_reason = forms.ChoiceField(
...,
choices=Model.CHOICES.subset('cancelled', 'failed', 'aborted')
)
```
In the mean time, we could subclass `Choices`, or write a helper function, but I figured I'd throw this together, as it seems like an entirely reasonable use of `Choices()`, that very well may help others.
That's the only change - the new method.  (And surrounding tests, documentation, etc.)
(I got to the part of `CONTRIBUTING.rst` that mentions I have to update `CHANGES.rst`, and got a little confused, so I also bumped the version.  Not …
> Added `Choices().subset()`.

- docs/utilities.rst
Having encountered this issue a couple of times with FieldTrackers, I thought it would be good to go in the docs! Hope this helps.
Generic FieldTrackers track ForeignKey Fields by db_column name, but there is no mention of this in the docs.
Issue #195 
Updated the docs.
> Update Docs - utilities.rst based on issue #195

- CHANGES.rst
- model_utils/fields.py
- model_utils/managers.py
- model_utils/models.py
- model_utils/tracker.py
- tests/fields.py
- tests/test_fields/test_field_tracker.py
- tests/test_managers/test_inheritance_manager.py
- tests/test_models/test_deferred_fields.py
- translations.py
> Remove unsupported django version hacks.

- CHANGES.rst
- model_utils/tracker.py
- tests/test_fields/test_field_tracker.py
FieldTracker does not track changes received with refresh_from_db. Steps to reproduce:
* update model instance "somewhere else": `Model.objects.filter(pk=obj.pk).update(field='new_in_db')`
* call `obj.refresh_from_db` with instance that is not syncrhonized with current db state
* `obj.field` is now marked as changed from 'old_py_value' to 'new_in_db', but really 'new_in_db' value is same in obj and in db
Mostly this bug affects test as a place of numerous `refresh_from_db` calls, but any pair of `refresh_fom_db()` + `tracker.changed()` may be incorrect.
Patch Model.refresh_from_db the same way as Model.save is patched in FieldTracker.
> patch Model.refresh_from_db in FieldTracker

- CHANGES.rst
- docs/utilities.rst
- model_utils/tracker.py
- tests/models.py
- tests/test_fields/test_field_tracker.py
If model with `FieldTracker` adds extra fields to `update_fields` in `save`, these changes are not reflected in FieldTracker state.
`FieldTracker` should patch `save_base` instead of `save`:
* `save_base` is called from `save` so final `update_fields` value is captured
* `save_base` is never overridden in `models.Model` subclasses
> FieldTracker should patch save_base instead of save 

- model_utils/models.py
- tests/test_models/test_timestamped_model.py
to update modified field automatically when update_fields argument is used but modified was not given as a parameter.
When the save method was called with the 'update_fields' argument, the 'modified' field was not automatically updated when it was forgotten to be given as a parameter. This may lead to future confusion since developers may not be aware of this functionality, and it is more logical to expect this field to be updated even if it is not provided inside the 'update_fields'
I've overrided the save method of the TimeStampedModel in order to support this functionality.
Unit tests on our product Plentific seems to work fine and as expected.
> Overriding TimeStampedModel's save() method

- CHANGES.rst
- model_utils/models.py
There is a deprecation warning for uggettext_lazy when running under Django 3.0.3.
`/home/martin/wks/redacted/venv3/lib/python3.6/site-packages/model_utils/models.py:28: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
created = AutoCreatedField(_('created'))
/home/martin/wks/redacted/venv3/lib/python3.6/site-packages/model_utils/models.py:29: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
modified = AutoLastModifiedField(_('modified'))
/home/martin/wks/redacted/venv3/lib/python3.6/site-packages/model_utils/models.py:41: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of …
> Satisfy deprecation warning under Django 3.0.3

- docs/utilities.rst
Adding docs so others can discover enumeration types. Could also consider deprecating, at least when minimum supported Django is 3.0.
> Document Django 3.0 enumeration types by 'Choices'

- tox.ini
The tox `deps` configuration refers to `django20x`, but the `envlist` uses `django2x`.
I fixed the discrepancy.  I haven't tested it locally, because I'm getting `psycopg2.OperationalError: could not connect to server`.
> Fix tox django factors

- model_utils/tracker.py
Django dropped model argument from DeferredAttribute more than 2 years ago
https://github.com/django/django/commit/c86e9b5847bc2853fc6a3fcfbf8daa56786d3210#diff-1e7fc0d7d1b36358e371fab97bd1ddb1L118
Using `.defer` or raw sql with few fields brokes tracker.
Removed model argument from DeferredAttributeTracker
> removed model from DeferredAttributeTracker

- CHANGES.rst
- model_utils/managers.py
- tests/test_managers/test_inheritance_manager.py
When calling `select_related()` with an empty list of arguments (1), Django will
try to prefetch some data by doing some first level joints with the related
classes.
This can lead to obvious negative performance impact, but this also breaks some
workarounds for having inheritance for foreign keys (2), as those solutions rely
on lazy evaluation of the related object.
(1): https://github.com/django/django/blob/a4e6030904df63b3f10aa0729b86dc6942b0458e/django/db/models/query.py#L1051
Only passing an explicit `None` to `select_related` will disable the magic.
(2): https://github.com/jazzband/django-model-utils/issues/11
As examples, here are the generated SQL requests in
InheritanceManagerRelatedTests.test_get_method_with_select_subclasses_check_for_useless_join:
* without this fix, without …
> managers: avoid querying too much tables when not needed

- tests/test_inheritance_iterable.py
- tests/test_managers/test_inheritance_manager.py
- tests/test_managers/test_join_manager.py
Running the tests emits a number of deprecation warnings like this:
```
tests/test_managers/test_join_manager.py::JoinManagerTest::test_reverse_join
/Users/craiga/django-model-utils/tests/test_managers/test_join_manager.py:36: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(items.count(), 1)
```
Rename methods as described in error message :)
> Change assert calls to avoid deprecation warnings.

- AUTHORS.rst
- CHANGES.rst
- docs/models.rst
- model_utils/managers.py
- model_utils/models.py
- tests/test_models/test_softdeletable_model.py
As described in #364
* Adds `.available_objects` manager to soft deletable models.
* Keeps existing `.objects` manager, but emits a `DeprecationWarning` for each use of that manager.
> Add available_objects soft deletable model manager

- CHANGES.rst
- setup.py
- tox.ini
> Add support for Django 3.1

- AUTHORS.rst
- CHANGES.rst
- model_utils/models.py
- tests/test_models/test_status_model.py
It is possible to forget to add it to update_fields and the purpose of the automatically updated status_changed field is lost.
Add status_changed field to upload_fields parameter during save if status field is present
> Add status_changed field to upload_fields parameter during save if status field is present

- model_utils/models.py
- requirements-test.txt
- tests/models.py
- tests/test_models/test_timestamped_model.py
- tox.ini
There are a few issues with current implementation of `TimeStamped.save()` method related to how it handles the `update_fields` argument.
Here's how current implementation diverges from [Django docs](https://docs.djangoproject.com/en/3.1/ref/models/instances/#specifying-which-fields-to-save):
1. It expects `update_fields` to be a `list`, while it can be any iterable:
> The update_fields argument can be any iterable containing strings.
2. When passed an empty list, it will add `modified` to it thus triggering an unexpected save:
> An empty update_fields iterable will skip the save.
3. Explicitly passing `update_fields=None` causes `TypeError`, while it's a valid value:
> A value of None will perform an update on all fields.
This PR adds a few checks to `TimeStamped.save` method to ensure …
> Issues with TimeStamped model's 'modified' and 'update_fields'

- model_utils/tracker.py
I noticed this typo when looking at an object's  `__dict__` in the Django shell.
I corrected the typo. This should have no effect on the behavior of the code.
> Fix typo in model_utils.tracker

- tests/models.py
Related to https://github.com/jazzband/django-model-utils/commit/6fba04ec4ff32b34cca61c6f1770ef6e81a40e2b.
> Replace ugettext_lazy with gettext_lazy in test models to satisfy Django deprecation warning.

- model_utils/managers.py
- model_utils/tracker.py
- tests/test_inheritance_iterable.py
Since we don't support Django < 2.2 we can remove parts of code that handle them.
> Remove codes related to old versions of Django.

- setup.cfg
No longer required as Python 2 support is deprecated
> Removed universal wheel builds

- CHANGES.rst
- model_utils/models.py
- tests/models.py
- tests/test_models/test_timestamped_model.py
Fixed https://github.com/jazzband/django-model-utils/issues/465
> Fixes save error when model inherit from both TimeStampModel and StatusModel.

- requirements-test.txt
- tests/test_models/test_timestamped_model.py
Improve tests:
* Remove `test_save_with_update_fields_updates_modified_even_when_it_is_not_included_in_a` because it's duplicate of `test_save_with_update_fields_overrides_modified_provided_within_a`
* Rewrite test by `subTest` and remove `parameterized` test dependancy
> Improve tests

- CHANGES.rst
- setup.py
- tox.ini
> Add support for Django 3.2 and drop support for Django 3.0

- AUTHORS.rst
- CHANGES.rst
- docs/fields.rst
- model_utils/fields.py
- tests/test_fields/test_urlsafe_token_field.py
A new `UrlsafeTokenField` is added under fields.
> Added urlsafe token field

- CHANGES.rst
- docs/utilities.rst
- model_utils/tracker.py
- tests/settings.py
- tests/test_fields/test_field_tracker.py
* There are breaking changes in `FieldTracker` state reset behavior described in #491
* Some people need old behavior, another new one
This PR introduces `FieldsContext` context manager which allows to postpone state reset till outermost context exit
Closes #491
> #491 Context manager for resetting fields

- model_utils/managers.py
Tests are failing agains django main branch (post-3.2) because of `QuerySet._chain` signature change, see https://github.com/django/django/pull/14755/files:
```
def _chain(self, **kwargs): ...
def _chain(self): ...
```
Update additional fields manually
> Fix QuerySet._chain for django main (post-3.2)

- tests/settings.py
When running test and the DB_HOST is not defined, tests would fail.
Set the deafult `DB_HOST` to be localhost, since this the usual scinario, specially when running locally.
> set deafult DB_host as localhost

- pre-commit-config.yaml
Someone added the pre-commit.ci check to the repository, but since there is no `.pre-commit.config.yaml` to read the check fails. This means there are a ton of red X's on the PR screen. I hate red X's.
This PR introduces a sensible starting `.pre-commit.config.yaml`, with the `isort`, `black`, and `flake8` hooks enabled, plus a few hooks from pre-commit itself.
This PR only includes the config file, it does not include any files changed by running `pre-commit run --all-files`. Doing so would touch 36 files across the project. However, if this PR is merged, it will be run and those 36 files will have to be addressed, otherwise it will just result in more red X's. My stance about red X's has already been covered. Don't like em.
> Add initial `.pre-commit.config.yaml`

- .pre-commit-config.yaml
Without this, it is failing with:
```
An error has occurred: InvalidConfigError:
=====> .pre-commit-config.yaml is not a file
```
... locally, and [on pre-commit.ci](https://results.pre-commit.ci/run/github/367233/1638617692.MJfSfSpAStKRpS_gf4Wieg).
Use the expected filename
- [n/a] Write PEP8 compliant code.
- [n/a] Cover it with tests.
- [n/a] Update `CHANGES.rst` file to describe the changes, and quote according issue with `GH-<issue_number>`.
- [n/a] Pay attention to backward compatibility, or if it breaks it, explain why.
- [n/a] Update documentation (if relevant).
> Fix name of pre-commit file

- docs/managers.rst
- model_utils/managers.py
- tests/test_models/test_timestamped_model.py
There are small typos in:
- docs/managers.rst
- model_utils/managers.py
- tests/test_models/test_timestamped_model.py
Fixes:
- Should read `subclasses` rather than `subclasess`.
- Should read `queryset` rather than `querset`.
- Should read `permissible` rather than `permissable`.
- Should read `modified` rather than `modifed`.
- Should read `heterogeneous` rather than `heterogenous`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- CHANGES.rst
- model_utils/managers.py
The workaround was for an issue that was fixed in Django 1.7: https://code.djangoproject.com/ticket/16855 / https://github.com/django/django/commit/349c12d3f5c015c2f8b36917da21230c2ac1acb4 .
Remove workaround.
> Remove workaround from select_subclasess()

- .github/workflows/test.yml
- .pre-commit-config.yaml
- CHANGES.rst
- README.rst
- docs/setup.rst
- model_utils/managers.py
- setup.py
- tests/models.py
- tests/test_managers/test_join_manager.py
- tox.ini
> Update support of Python and Django versions

- CHANGES.rst
Release 4.3.0 with the changes buffered up since 4.2.0 was released more than a year ago. I've confirmed that the changelog covers all changes added since 4.2.0 using `git diff 4.2.0 master`.
Fixes https://github.com/jazzband/django-model-utils/issues/546
> Release 4.3.0.

- CHANGES.rst
This is basically what was meant to be 4.3.0 but failed [due to RST errors in the CHANGELOG](https://github.com/jazzband/django-model-utils/actions/runs/3475135483/jobs/5809031610) 🤦 
This makes be think we should likely run `twine check dist/*` on CI for PR as well.
> Release 4.3.1.

- tox.ini
If I try to run the unit tests via `tox`, I get this error:
```
File "<snip>/site-packages/pytest_django/plugin.py", line 174, in _handle_import_error
raise ImportError(msg)
ImportError: No module named 'tests'
```
This problem is triggered when `pytest-django` tries to load the module `tests.settings` as defined by `DJANGO_SETTINGS_MODULE`.
I saw a similar error in your CI, so I think it's not a problem of my local setup, but rather something that broke when one of the tooling packages changed its behavior.
Invoke pytest using `python -m pytest` instead of just `pytest`.
https://docs.pytest.org/en/6.2.x/usage.html#calling-pytest-through-python-m-pytest
Before stumbling upon this solution, tried to specify `pythonpath=.`  in `setup.cfg`, but that setting seems to only take effect after …
> Fix "ImportError: No module named 'tests'"

- CHANGES.rst
- setup.py
- tox.ini
With the release of django 4.2 the classifiers needs to be updated and the tests needs to be run against the 4.2 branch.
> Test django against 4.2 & main branch to formally support django 4.2

- CHANGES.rst
- requirements-test.txt
- setup.py
- tox.ini
Test the new version of Django that’s in beta.
Depends on #582. If you want to consider updating `SaveSignalHandlingModel`, we can look at that, but I really suggest that it be removed.
Added classifier to `setup.py`, new test environment to `tox.ini`, setup, and upgraded test requirements to fix some warnings.
> Test Django 5.0

- AUTHORS.rst
- CHANGES.rst
- docs/utilities.rst
- model_utils/tracker.py
In one of the latest versions, sentry-sdk added logging of the launch of django signal handlers. Due to the fact that the `post_init` signal handler is used to initialize the tracker, this leads to a significant decrease in performance, and also occupies the sentry logs with useless entries, which makes it impossible to analyze performance in Sentry
Don't use `post_init` signal for initialize tracker
> Don't use `post_init` signal for initialize tracker

- docs/models.rst
follow-up to https://github.com/jazzband/django-model-utils/pull/438/
https://github.com/jazzband/django-model-utils/pull/438/ added docs explaining the deprecation, but as a result it became unclear which manager one should use to return all objects (until https://github.com/jazzband/django-model-utils/pull/480 can be merged)
> clarify docs for managers of SoftDeletableModel

- tests/test_models/test_softdeletable_model.py
`ConnectionDoesNotExist` does not exist in `django.db.utils` in `django-stubs`, as it was moved to `django.utils.connection` in Django 3.2.  At some point in the future, I expect it will also only be available from its new location in Django itself.
Import it from its new location.
> Update where `ConnectionDoesNotExist` is imported from

- model_utils/managers.py
`InheritanceQuerySetMixin._clone()` accepts and then ignores a `klass` and `setup` argument, plus any keyword arguments. The `QuerySet._clone()` method has no arguments in either Django 3.2 or 4.1 and when using a static code checker like `mypy`, this is reported as incompatible base classes for `InheritanceManager`.
I'm assuming the arguments were necessary for a version of Django that is no longer supported by `django-model-utils`. Therefore I removed the extra arguments.
I chose to not add an entry in `CHANGES.rst`, as this is a cleanup that should not be noticeable to users.
> Remove arguments from `InheritanceQuerySetMixin._clone()`

- tests/settings.py
Distro build workers do not want to install postgres in order to run the tests.
Added capability to use sqlite instead using env flag `SQLITE`
> Allow running tests using sqlite

- CHANGES.rst
- model_utils/fields.py
- tests/test_fields/test_monitor_field.py
I recently came across a non-intuitive behavior, IMHO. The MonitorField has its default value set to now even though marked as nullable. Please, I'm open to hearing the opinion case this is expected behavior.
After catching up the discussion in https://github.com/jazzband/django-model-utils/issues/100 I decided to implement it. The discussed solution is to set its default value to None when null=True.
If **might break** backward compatibility at the edge case of someone marking the field as null=True and not expecting default to be None.
> `MonitorField` - Change default to None when the field is nullable 

- model_utils/__init__.py
By listing names intended for export in the `__all__` module-level variable, static code checkers like mypy are able to verify that importing a name from a module that itself imported it is by design rather than by accident.
As flake8 understand `__all__`, this also removes the need for warning suppression comments.
> Explicitly re-export names from `__init__` module

- requirements.txt
- tests/test_fields/test_monitor_field.py
- tests/test_models/test_status_model.py
- tests/test_models/test_timestamped_model.py
- tox.ini
freezegun is slow.
time-machine is [more accurate](https://adamj.eu/tech/2020/06/03/introducing-time-machine/) and [faster](https://adamj.eu/tech/2021/02/19/freezegun-versus-time-machine/).
- [n/a] Update `CHANGES.rst` file to describe the changes, and quote according issue with `GH-<issue_number>`.
- [n/a] Pay attention to backward compatibility, or if it breaks it, explain why.
- [n/a] Update documentation (if relevant).
> Switch from freezegun to time-machine.

- tests/settings.py
In #510 timezones are added to the asserts but since the test project didn't used timezones all tests where are failing
> USE_TZ = True

- tests/models.py
The `JoinManager` class already exists in `model_utils.managers`, with the exact same definition.
> Remove redundant definition of `JoinManager` from tests

- tests/test_fields/test_field_tracker.py
The `@skip` decorator works without an argument as well, but that is an undocumented feature of [`unittest.skip()`](https://docs.python.org/3/library/unittest.html#unittest.skip) that is not understood by mypy and pytest.
In the case of pytest, it ignored the decorated class during test collection, instead of collecting it and marking it as skipped.
> Pass reason to `@skip` decorator

- tests/models.py
- tests/test_models/test_status_model.py
In `tests/models.py`, there were two classes named `StatusCustomManager`: the first is an actual manager, the second a status model that uses a custom manager. The latter is renamed to `CustomManagerStatusModel` in this PR.
The name clash tripped up mypy, but is also confusing for human readers.
> Resolve name clash among test models

- tests/signals.py
This module was support code for the `SaveSignalHandlingModel` tests. That class got introduced in 5d6f8f4e and removed in 11f3a53b, but the support code remained.
> Remove obsolete `tests.signals` module

- tests/models.py
This PR removes a bunch of obsolete classes from `tests/models.py`. The tests that used them were removed long ago, but the test models escaped deletion, until now.
> Remove obsolete test models

- .github/workflows/test.yml
- CONTRIBUTING.rst
- docker-compose.yml
- tests/settings.py
- tox.ini
It took me some minutes to figure out what is required to run the tests locally. This PR updates the environment variables so they align with the postgres docker container and adds a docker-compose.yml to have a testing database without persisting volume.
> Postgresql docker container for local development

- .github/workflows/issue-manager.yml
> Automatically close issues or Pull Requests that have a label, after a custom delay, if no one replies back.
This PR adds https://github.com/tiangolo/issue-manager to the github workflows. The config is borrowed from [cookiecutter-django](https://github.com/cookiecutter/cookiecutter-django/). 
It will help closing issues and PR's without any wrongdoing against the original poster.
> Add issue-manager

- model_utils/fields.py
The use of `isinstance(factory, Callable)` is avoided, because it triggers a long standing bug in mypy.
Additionally, a wrong word in an error message was fixed.
This should have no impact on users of the library.
> Minor cleanup of the code handling `UrlsafeTokenField`'s `factory` argument

- model_utils/fields.py
- tests/test_fields/test_field_tracker.py
Python 2 didn't have keyword-only arguments, so some code emulated them by wrangling `kwargs`. This PR updates that code to use modern syntax instead.
There should be no backwards compatibility issues.
> Modernize the way some keyword-only arguments are implemented

- CHANGES.rst
- model_utils/fields.py
- tests/models.py
The `contribute_to_class()` methods in `StatusField`, `MonitorField` and `SplitField` were not passing on additional arguments to Django, which means the `private_only` argument and any future arguments could not be used. This PR fixes that by accepting and forwarding any additional arguments.
> Forward additional arguments to `contribute_to_class()` to Django

- model_utils/fields.py
This code was using old property syntax instead of `@property` decorators.
I also removed the comments, as they don't express anything that isn't already clear from the code itself.
> Modernize property definitions in `SplitText`

- model_utils/managers.py
Looking into the uncovered lines of code (at this moment 757 out of 768 lines are covered) I noticed that the `levels` variable in `managers.py` is never being set apart from `None`.
According to the test-suite it can be removed safely. 
Can someone review this removal?
> Levels variable is never set

- model_utils/__init__.py
- mypy.ini
- requirements-mypy.txt
- tests/models.py
- tests/settings.py
- tests/test_fields/test_field_tracker.py
- tox.ini
This is a first step in adding type annotations. See #558 for discussion.
Some things to pay attention to during review:
I'm using `from __future__ import annotations` to force postponed evaluation of annotations. This has several advantages:
- it allows modern syntax like `dict[str, str]` or `int | None` to be used in Python versions where the interpreter doesn't support that syntax yet
- it avoids most problems when using a type argument to for example `QuerySet` in Django 3.2, where `QuerySet` does not yet inherit from `typing.Generic`
- it allows using types in annotations that are defined later in the source file
- it allows using types in annotations that we can't import at runtime because it would create a circular import
I added `typing_extensions` as a runtime dependency. This …
> Enable static type checks using mypy in CI

- CHANGES.rst
- model_utils/fields.py
South FakeORM hasn't been supported since fda2d39e, but the workaround introduced in 9147becf evaded deletion. The `NoRendered` model was removed in 9df3df99, but with that model gone, the `no_excerpt_field` argument became obsolete as well.
> Remove excerpt field workaround for South FakeORM

- CHANGES.rst
- model_utils/models.py
The `soft` argument was made keyword-only, to avoid conflicts with new positional arguments that might be added to Django. It was already conflicting with the `keep_parents` argument.
This is a backward incompatible change: code that used to pass `soft` positionally will require updating. Hopefully most code was either using the default (`True`) or was already passing `soft=False` as a keyword argument.
> Fix `SoftDeletableModel.delete()` forwarding positional args to superclass

- tests/managers.py
- tests/models.py
- tests/test_managers/test_softdelete_manager.py
Besides requiring less code, this also allows the django-stubs mypy plugin to automatically generate a type-annotated version of the manager.
Name the manager `available_objects` because `objects` is deprecated in `SoftDeletableModel`.
> Auto-generate manager implementation for `CustomSoftDelete`

- model_utils/managers.py
Pass the parameters to the DB API instead of quoting them ourselves.
> Remove `JoinQueryset.get_quoted_query()`

- model_utils/fields.py
- tests/test_fields/test_split_field.py
This behavior wasn't documented and didn't fully work: it breaks as soon as you try to save a model with a `None` value.
I think removing `None` support is better than making it work:
- to make it work properly, it would have to respect the `null` constructor argument both in the implementation and in the type checking, which is a lot of work
- [the Django docs](https://docs.djangoproject.com/en/5.0/ref/models/fields/#null) recommend against using `null=True` for text fields, so the value of the feature is questionable
As it was an undocumented feature that only partially worked, I think this change doesn't break backwards compatibility, so I didn't add it to the ChangeLog.
> Remove support for assigning `None` to a `SplitField`

- model_utils/tracker.py
- tests/models.py
- tests/test_fields/test_field_tracker.py
I was cleaning up the type annotations in `DescriptorWrapper.__get__()`:
```py
def __get__(self, instance: models.Model | None, owner: type[models.Model]) -> DescriptorWrapper[T] | T:
if instance is None:
return self
was_deferred = self.field_name in instance.get_deferred_fields()
try:
value = self.descriptor.__get__(instance, owner)
except AttributeError:
value = self.descriptor
if was_deferred:
tracker_instance = getattr(instance, self.tracker_attname)
tracker_instance.saved_data[self.field_name] = lightweight_deepcopy(value)
return value
```
After being puzzled by the code for some time, I realized that the `value = self.descriptor` statement was inherently incompatible with the return type of the method. Also storing the descriptor rather than a value in `tracker_instance.saved_data` …
> Remove catching of `AttributeError` in `DescriptorWrapper`

- .coveragerc
- model_utils/choices.py
- model_utils/fields.py
- model_utils/managers.py
- model_utils/models.py
- model_utils/tracker.py
- mypy.ini
- requirements-mypy.txt
- tests/fields.py
- tests/models.py
- tests/test_choices.py
- tests/test_fields/test_field_tracker.py
- tests/test_fields/test_monitor_field.py
- tests/test_fields/test_split_field.py
- tests/test_fields/test_status_field.py
- tests/test_fields/test_urlsafe_token_field.py
- tests/test_fields/test_uuid_field.py
- tests/test_inheritance_iterable.py
- tests/test_managers/test_inheritance_manager.py
- tests/test_managers/test_join_manager.py
- tests/test_managers/test_query_manager.py
- tests/test_managers/test_softdelete_manager.py
- tests/test_managers/test_status_manager.py
- tests/test_miscellaneous.py
- tests/test_models/test_deferred_fields.py
- tests/test_models/test_softdeletable_model.py
- tests/test_models/test_status_model.py
- tests/test_models/test_timeframed_model.py
- tests/test_models/test_timestamped_model.py
- tests/test_models/test_uuid_model.py
This implements the bulk of the changes required for #558. The annotations are still a bit rough, but they have reached a stage where testing with third party code would be useful.
> Add type annotations

- CHANGES.rst
- setup.py
- tox.ini
The project has already been tested against the Django main branch, so no additional changes are needed to support Django 5.1.
> Add formal support for django 5.1

- CHANGES.rst
- model_utils/managers.py
- tests/test_models/test_softdeletable_model.py
Mimics Django's API for `SoftDeletableQuerySetMixin`.
Django's API behaves as the [following](https://docs.djangoproject.com/en/5.0/topics/db/queries/#deleting-objects):
Returning a tuple of type (int, dict[str, int]) where the first element is the number of objects deleted and the second the same count but for the model itself and its relations.
The proposed solution returns the number of objects affected by the update and a made up dict where the key is model's label (no relations as we don't touch it) with aforementioned count.
> chore: Replicate Django's signature at SoftDelete queryset

- AUTHORS.rst
- model_utils/tracker.py
- tests/models.py
- tests/test_fields/test_field_tracker.py
When deleting a model, that has a reverse relationship to a tracked model with SET_NULL on_delete
This issue arrises on these conditions:
1. You delete a model that is target of a foreign key, with `on_delete=SET_NULL` (I believe also with PROTECT)
2. The related model that is going to be deleted has a field tracker that tracks a foreign key field
When this happens, django loads the instance from the db with all fields deferred other than id.  In this code,
```
def current(self, fields=None):
if fields is None:
deferred_fields = self.deferred_fields
if deferred_fields:
fields = [
field for field in self.fields
if field not in deferred_fields
]
else:
fields = self.fields
return {f: self.get_field_value(f) for f in fields}
```
we skip those deferred fields, but this is where the issue …
> Fixed an infinite recursion bug when deleting models related to a tracked model with a ForeignKey
